spring:
  application:
   name: ai-coder-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api

#langchain4j:
#  community:
#    dashscope:
#      chat-model:
#        api-key: ""
#        model-name: "qwen-plus"
#      streaming-chat-model:
#        model-name: "qwen-plus"
#        api-key: ""
#
#bigmodel:
#  api-key:
